[package]
name = "newt-sys"
version = "0.1.0"
authors = ["Robert Gill <locke@sdf.lonestar.org>"]
description = "Low-level bindings for the Newt console UI library"
license = "LGPL-2.0-only"
readme = "README.md"

links = "newt"
build = "build.rs"

[build-dependencies]
pkg-config = "0.3.14"
